version: '3'

services:
    db:
        image: postgres:14.4
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=django
            - POSTGRES_USER=django
            - POSTGRES_PASSWORD=django
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U django"]
            interval: 10s
            timeout: 5s
            retries: 5
    web:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_NAME=django
            - DB_USER=django
            - DB_PASS=django
            - DB_HOST=db
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure:1
        command: "python manage.py runserver 0.0.0.0:8000"

volumes:
    postgres_data:
